version: 2

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64   # 64-bit
      - 386     # 32-bit
      - arm     # ARM (32-bit)
      - arm64   # ARM (64-bit)

    binary: kaizen

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Tag }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else if eq .Arch "arm" }}arm
      {{- else if eq .Arch "arm64" }}arm64
      {{- else }}{{ .Arch }}{{ end }}
